### ISSUE TITLE
Updating C++ wrapper for 0.8 - Happy to make a PR

### ISSUE THREAD

**Issue by mipals** [oxfordcontrol/Clarabel.cpp#38]
Hi there,

I wanted to try out the Chordal decomposition added in 0.8 using the C++ wrapper. Turned out I needed to do a few modifications to the wrapper due to the API additions. At the same time I noticed that a few tests were missing, so I added them. The changes can be seen on [my fork](https://github.com/mipals/Clarabel.cpp/tree/development)

If you want I can make a PR. That being said, I am not very experienced in C++ and Rust, so my code is probably substandard. 

Cheers,
Mikkel

**Comment by goulart-paul** [comment]
I upgraded the wrappers already in the `develop` branch, and I don't now remember why I didn't merge it.   I will take a look.

**Comment by mipals** [comment]
I do not know why I did not think of checking other branches. Well, I can migrate the missing tests to the `develop` branch.

**Comment by goulart-paul** [comment]
I have merged an update to v0.8.1 to main in #39.   I haven't tagged it as v0.8.1 here yet.    Tests are good, so happy to have include more tests if you have them.

**Comment by mipals** [comment]
Thanks for the update. I will make a PR adding the tests.

**Comment by goulart-paul** [comment]
Thanks.   I have merged both the develop branch and your tests from #40, which I think resolves this issue.
